# golangci-lint configuration (v2.x compatible)
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (github.com/gin-gonic/gin.IRoutes).POST
      - (github.com/gin-gonic/gin.IRoutes).GET
      - (github.com/gin-gonic/gin.IRoutes).PUT
      - (github.com/gin-gonic/gin.IRoutes).DELETE
      - (*github.com/gin-gonic/gin.RouterGroup).POST
      - (*github.com/gin-gonic/gin.RouterGroup).GET
      - (*github.com/gin-gonic/gin.RouterGroup).PUT
      - (*github.com/gin-gonic/gin.RouterGroup).DELETE
      - (*github.com/gin-gonic/gin.Engine).Use
      - (github.com/gin-gonic/gin.IRoutes).Use
  
  govet:
    enable:
      - shadow
  
  misspell:
    locale: US

formatters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/holygeek00/lite-sdwan

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    - linters:
        - staticcheck
      text: "SA1019:"

  max-issues-per-linter: 50
  max-same-issues: 10
